In [18]:
#Desarrollar una automatización que permita extraer e interpretar la data del archivo Student-mat.csv y 
#Student-por.csv de manera que una la información solicitada de ambos archivos y realice los requerimientos solicitados 


import pandas as pd
import datetime
import matplotlib.pyplot as plt
from pandas import Series, DataFrame


    

data= pd.read_csv('student-mat.csv', sep= ';')



df_mat= data[['school', 'sex', 'age', 'address', 'Pstatus', 'guardian', 'traveltime', 'studytime', 'failures', 'paid', 'internet', 'health', 'absences', 'G1','G2','G3'
]]
#df_mat

df_mat_sep= df_mat.groupby(['school'])
df_mat_sep



#gp_mat= df_mat_sep(['GP'])

for key,group in df_mat_sep:
    
   
    if key== 'GP':
           gp_mat= group
            
    elif key== 'MS':
           ms_mat= group

data2= pd.read_csv('student-por.csv', sep= ';')


df_por= data2[['school', 'sex', 'age', 'address', 'Pstatus', 'guardian', 'traveltime', 'studytime', 'failures', 'paid', 'internet', 'health', 'absences', 'G1','G2','G3'
]]

df_por_sep= df_por.groupby(['school'])


for key,group in df_por_sep:
    
   
    if key== 'GP':
           gp_por= group
            
    elif key== 'MS':
           ms_por= group
            
#df_mat -> ambas escuelas mat
#df_mat_sep -> ambas escuelas filtradas(group by)
#gp_mat
#ms_mat
#df_por -> ambas escuelas mat
#df_por_sep -> ambas escuelas filtradas(group by)
#gp_por
#ms_por













t_est_df_mat= len(df_mat)
print("t_est_df_mat= ",t_est_df_mat)

t_est_df_mat_sep_sex= df_mat.groupby(['sex'])

for key,group in t_est_df_mat_sep_sex:
    
   
    if key== 'M':
           t_m_df_mat_df= group
            
    elif key== 'F':
          t_f_df_mat_df = group

t_m_df_mat=len(t_m_df_mat_df)
print("t_m_df_mat= ",t_m_df_mat)

porcentaje_de_h= t_m_df_mat/t_est_df_mat *100
print(porcentaje_de_h)

t_m_df_mat=len(t_m_df_mat_df)
print("t_m_df_mat= ",t_m_df_mat)

porcentaje_de_f= t_m_df_mat/t_est_df_mat *100
print(porcentaje_de_f)





##################################  edades

gp_mat

edades_gp_mat=gp_mat.groupby(["age"])
edades_gp_mat

print("________________")

lst_inx_edades=[]
lst_val_cantidad=[]

################################# print de ejemplo, prueba de escritorio###################
for key,group in edades_gp_mat:
    
    #print("+key ", key)
    #print("+number ", len(group))
    #print(group.head())
    #print("\n")
    
    lst_inx_edades.append(key)
    lst_val_cantidad.append(len(group))
    
    
gp_mat

t_est_df_mat=  395
t_m_df_mat=  187
47.34177215189874
t_m_df_mat=  187
47.34177215189874
________________

,school,sex,age,address,Pstatus,guardian,traveltime,studytime,failures,paid,internet,health,absences,G1,G2,G3
0,GP,F,18,U,A,mother,2,2,0,no,no,3,6,5,6,6
1,GP,F,17,U,T,father,1,2,0,no,yes,3,4,5,5,6
2,GP,F,15,U,T,mother,1,2,3,yes,yes,3,10,7,8,10
3,GP,F,15,U,T,mother,1,3,0,yes,yes,5,2,15,14,15
4,GP,F,16,U,T,father,1,2,0,yes,no,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,GP,F,18,U,T,mother,1,3,0,no,yes,3,4,11,10,10
345,GP,F,18,U,T,mother,1,3,0,no,yes,1,7,13,13,14
346,GP,M,18,R,T,mother,1,3,0,no,yes,4,9,16,15,16
347,GP,M,18,U,T,mother,1,3,0,yes,yes,5,0,10,10,9
348,GP,F,17,U,T,mother,1,3,0,yes,yes,4,0,13,15,15

In [ ]:
today = str(datetime.date.today())
name= "Resultado_" + today+".csv"

GP_mat.to_csv(name, header = True, index = False)
GP_por.to_csv(name, header = True, index = False, mode="a")
MS_mat.to_csv(name, header = True, index = False, mode="a")
MS_por.to_csv(name, header = True, index = False, mode="a")